layout_spectrum: 0.3141783
color:
  saturation: 0.7835661
  brandStrength: 0.06901821
  lightness: 0.5398403
  rhythmicContrast: 0.8782654
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.9307196
name: IoT Marketing
