name: IoT Marketing
favicon: null
layout_spectrum: 0.50167
typography_spectrum: 0.75413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d5d5'
    - '#474e63'
    - '#000000'
    - '#9f2504'
    - '#ebc318'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
